plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  "tag:Project": CloudDevOpsProject

keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""

hostnames:
  - public-ip-address

compose:
  ansible_host: public_ip_address
